services:
  api:
    profiles:
      - all
      - api
    build:
      context: .
      dockerfile: docker/app/DockerFile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - asterisk-net

  test-api:
    profiles:
      - test
    build:
      context: .
      dockerfile: docker/app/DockerFile
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: go test -v ./internal/handler
    depends_on:
      - redis
    networks:
      - asterisk-net

  redis:
    profiles:
      - all
      - api
      - asterisk
      - test
      - redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - asterisk-net

  asterisk:
    profiles:
      - all
      - asterisk
#    network_mode: host
    ports:
      - "50605:50605/udp"
    build:
      context: .
      dockerfile: docker/asterisk/Dockerfile
    restart: always
    volumes:
      - ./docker/asterisk/config:/etc/asterisk
    networks:
      - asterisk-net
    env_file:
      - .env

networks:
  asterisk-net:
    driver: bridge

volumes:
  redis_data: